# Form implementation generated from reading ui file 'AboutWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutUniHelp(object):
    def setupUi(self, AboutUniHelp):
        AboutUniHelp.setObjectName("AboutUniHelp")
        AboutUniHelp.resize(512, 230)
        AboutUniHelp.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    background-color: rgb(18, 18, 18);\n"
"    font-family: Open Sans;\n"
"}")
        self.label = QtWidgets.QLabel(parent=AboutUniHelp)
        self.label.setGeometry(QtCore.QRect(210, 10, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=AboutUniHelp)
        self.label_2.setGeometry(QtCore.QRect(210, 70, 291, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=AboutUniHelp)
        self.label_3.setGeometry(QtCore.QRect(210, 90, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=AboutUniHelp)
        self.label_4.setGeometry(QtCore.QRect(210, 130, 291, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=AboutUniHelp)
        self.label_5.setGeometry(QtCore.QRect(210, 150, 291, 16))
        self.label_5.setObjectName("label_5")
        self.frame = QtWidgets.QFrame(parent=AboutUniHelp)
        self.frame.setGeometry(QtCore.QRect(20, 20, 150, 150))
        self.frame.setStyleSheet("QFrame {\n"
"    background: url(\"./img/logo_min.png\");\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")

        self.retranslateUi(AboutUniHelp)
        QtCore.QMetaObject.connectSlotsByName(AboutUniHelp)

    def retranslateUi(self, AboutUniHelp):
        _translate = QtCore.QCoreApplication.translate
        AboutUniHelp.setWindowTitle(_translate("AboutUniHelp", "О UniHelp"))
        self.label.setText(_translate("AboutUniHelp", "Universal Helper"))
        self.label_2.setText(_translate("AboutUniHelp", "Universal Helper - программа помощник в учёбе."))
        self.label_3.setText(_translate("AboutUniHelp", "Авторы:"))
        self.label_4.setText(_translate("AboutUniHelp", "Чагаев Егор - SMS-Message"))
        self.label_5.setText(_translate("AboutUniHelp", "Ильясов Тимур - 4lTimich"))
