# Form implementation generated from reading ui file 'GraphWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Graphs(object):
    def setupUi(self, Graphs):
        Graphs.setObjectName("Graphs")
        Graphs.resize(765, 609)
        Graphs.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    background-color: rgb(18, 18, 18);\n"
"    font-family: Open Sans;\n"
"}\n"
"\n"
"Line {\n"
"    border: 1px;\n"
"    background:  #CCCCCC;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font-size: 24px;\n"
"    padding: 2px; \n"
"    background-color: rgb(20, 20, 20);\n"
"    border: solid;\n"
"    border-color: #353535;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"\n"
"    width: 50px;\n"
"    height: 40px;\n"
"    \n"
"    border: solid;\n"
"    border-color: #353535;\n"
"    border-width: 1px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: rgb(170, 170, 170);\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-color: white;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: #353535;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Graphs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=Graphs)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=Graphs)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.minEdit = QtWidgets.QLineEdit(parent=Graphs)
        self.minEdit.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        self.minEdit.setFont(font)
        self.minEdit.setObjectName("minEdit")
        self.horizontalLayout_3.addWidget(self.minEdit)
        self.label_4 = QtWidgets.QLabel(parent=Graphs)
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.maxEdit = QtWidgets.QLineEdit(parent=Graphs)
        self.maxEdit.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        self.maxEdit.setFont(font)
        self.maxEdit.setObjectName("maxEdit")
        self.horizontalLayout_3.addWidget(self.maxEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 2, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Graphs)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 6, 1, 1)
        self.graphEdit = QtWidgets.QLineEdit(parent=Graphs)
        self.graphEdit.setObjectName("graphEdit")
        self.gridLayout.addWidget(self.graphEdit, 1, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.runBtn = QtWidgets.QPushButton(parent=Graphs)
        self.runBtn.setMinimumSize(QtCore.QSize(150, 0))
        self.runBtn.setObjectName("runBtn")
        self.horizontalLayout.addWidget(self.runBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.returnBtn = QtWidgets.QPushButton(parent=Graphs)
        self.returnBtn.setMinimumSize(QtCore.QSize(300, 0))
        self.returnBtn.setObjectName("returnBtn")
        self.horizontalLayout_2.addWidget(self.returnBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Graphs)
        QtCore.QMetaObject.connectSlotsByName(Graphs)

    def retranslateUi(self, Graphs):
        _translate = QtCore.QCoreApplication.translate
        Graphs.setWindowTitle(_translate("Graphs", "Построение графиков"))
        self.label_2.setText(_translate("Graphs", "="))
        self.label_3.setText(_translate("Graphs", "От:"))
        self.label_4.setText(_translate("Graphs", "До:"))
        self.label.setText(_translate("Graphs", "y"))
        self.runBtn.setText(_translate("Graphs", "Построить"))
        self.returnBtn.setText(_translate("Graphs", "Вернуться"))
