# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 592)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(18, 18, 18);\n"
"    background-image: url(\'./img/background.png\');\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: qlineargradient(spread:pad, x1:0.472, y1:1, x2:0.482955, y2:0, stop:0 rgba(18, 18, 18, 123), stop:0.795455 rgba(35, 35, 35, 255));\n"
"    spacing: 3px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    color: #FFFFFF;\n"
"    padding: 1px 4px;\n"
"    background: transparent;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: #a8a8a8;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    background: #888888;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 2px;\n"
"    background: #353535;\n"
"}\n"
"\n"
"QMenu {\n"
"    color: #FFFFFF;\n"
"    background-color: #121212;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    color: #FFFFFF;\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QWidget {\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonsFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.buttonsFrame.setMaximumSize(QtCore.QSize(150, 300))
        self.buttonsFrame.setStyleSheet("QFrame {\n"
"    background-color: #121212;\n"
"\n"
"    border: solid;\n"
"    border-color: rgb(45,55,50);\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"\n"
"    width: 300px;\n"
"    height: 20px;\n"
"    \n"
"    border: solid;\n"
"    border-color: #353535;\n"
"    border-width: 1px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: rgb(170, 170, 170);\n"
"    border-width: 2px;\n"
"\n"
"    width: 300px;\n"
"    height: 30px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-color: white;\n"
"    border-width: 2px;\n"
"    \n"
"    width: 300px;\n"
"    height: 30px;\n"
"}\n"
"")
        self.buttonsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.buttonsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.buttons = QtWidgets.QVBoxLayout(self.buttonsFrame)
        self.buttons.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.buttons.setContentsMargins(5, 75, 5, 75)
        self.buttons.setSpacing(0)
        self.buttons.setObjectName("buttons")
        self.calcBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.calcBtn.setObjectName("calcBtn")
        self.tabsButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.tabsButtonGroup.setObjectName("tabsButtonGroup")
        self.tabsButtonGroup.addButton(self.calcBtn)
        self.buttons.addWidget(self.calcBtn)
        self.graphBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.graphBtn.setObjectName("graphBtn")
        self.tabsButtonGroup.addButton(self.graphBtn)
        self.buttons.addWidget(self.graphBtn)
        self.eqBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.eqBtn.setObjectName("eqBtn")
        self.tabsButtonGroup.addButton(self.eqBtn)
        self.buttons.addWidget(self.eqBtn)
        self.forLibBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.forLibBtn.setObjectName("forLibBtn")
        self.tabsButtonGroup.addButton(self.forLibBtn)
        self.buttons.addWidget(self.forLibBtn)
        self.bookLibButton = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.bookLibButton.setObjectName("bookLibButton")
        self.tabsButtonGroup.addButton(self.bookLibButton)
        self.buttons.addWidget(self.bookLibButton)
        self.horizontalLayout.addWidget(self.buttonsFrame)
        self.textFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.textFrame.setMinimumSize(QtCore.QSize(490, 0))
        self.textFrame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textFrame.setObjectName("textFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.textFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.mainLabel = QtWidgets.QLabel(parent=self.textFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mainLabel.setFont(font)
        self.mainLabel.setStyleSheet("QLabel {\n"
"    padding: 5px 5px 5px 5px;\n"
"    color: white;\n"
"    border: solid;\n"
"    border-color: #CCCCCC;\n"
"    border-width: 2px;\n"
"    border-radius: 16px;\n"
"}")
        self.mainLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mainLabel.setObjectName("mainLabel")
        self.verticalLayout.addWidget(self.mainLabel)
        self.label = QtWidgets.QLabel(parent=self.textFrame)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {color: white}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.textFrame)
        self.widgetsLayout = QtWidgets.QHBoxLayout()
        self.widgetsLayout.setObjectName("widgetsLayout")
        self.horizontalLayout.addLayout(self.widgetsLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 672, 19))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(parent=self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.closeWinsAction = QtGui.QAction(parent=MainWindow)
        self.closeWinsAction.setObjectName("closeWinsAction")
        self.exitAction = QtGui.QAction(parent=MainWindow)
        self.exitAction.setObjectName("exitAction")
        self.authorsAction = QtGui.QAction(parent=MainWindow)
        self.authorsAction.setObjectName("authorsAction")
        self.menu.addAction(self.closeWinsAction)
        self.menu.addSeparator()
        self.menu.addAction(self.exitAction)
        self.menu_2.addAction(self.authorsAction)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UniHelp"))
        self.calcBtn.setText(_translate("MainWindow", "Калькулятор"))
        self.graphBtn.setText(_translate("MainWindow", "Графики"))
        self.eqBtn.setText(_translate("MainWindow", "Уравнения"))
        self.forLibBtn.setText(_translate("MainWindow", "Библиотека формул"))
        self.bookLibButton.setText(_translate("MainWindow", "Библиотека учебников"))
        self.mainLabel.setText(_translate("MainWindow", "Universal Helper"))
        self.label.setText(_translate("MainWindow", "Выберите вкладку слева"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Справка"))
        self.closeWinsAction.setText(_translate("MainWindow", "Закрыть все окна"))
        self.exitAction.setText(_translate("MainWindow", "Выход"))
        self.authorsAction.setText(_translate("MainWindow", "Авторы"))
