# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(837, 592)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(18, 18, 18);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonsFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.buttonsFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(18, 18, 18);\n"
"    \n"
"    border: solid;\n"
"    border-color: rgb(45,55,50);\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    background: rgb(65, 65, 65);\n"
"    \n"
"    width: 300px;\n"
"    height: 20px;\n"
"    \n"
"    border: solid;\n"
"    border-color: black;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: rgb(170, 170, 170);\n"
"    border-width: 2px;\n"
"\n"
"    width: 300px;\n"
"    height: 30px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-color: white;\n"
"    border-width: 2px;\n"
"    \n"
"    width: 300px;\n"
"    height: 30px;\n"
"}\n"
"")
        self.buttonsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.buttonsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.buttons = QtWidgets.QVBoxLayout(self.buttonsFrame)
        self.buttons.setContentsMargins(20, 150, 30, 300)
        self.buttons.setSpacing(5)
        self.buttons.setObjectName("buttons")
        self.calcBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.calcBtn.setObjectName("calcBtn")
        self.buttons.addWidget(self.calcBtn)
        self.graphBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.graphBtn.setObjectName("graphBtn")
        self.buttons.addWidget(self.graphBtn)
        self.eqBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.eqBtn.setObjectName("eqBtn")
        self.buttons.addWidget(self.eqBtn)
        self.forLibBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.forLibBtn.setObjectName("forLibBtn")
        self.buttons.addWidget(self.forLibBtn)
        self.bookLibButton = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.bookLibButton.setObjectName("bookLibButton")
        self.buttons.addWidget(self.bookLibButton)
        self.horizontalLayout.addWidget(self.buttonsFrame)
        self.textFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.textFrame.setObjectName("textFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.textFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.mainLabel = QtWidgets.QLabel(parent=self.textFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mainLabel.setFont(font)
        self.mainLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    border: solid;\n"
"    border-color: rgb(45, 45, 45);\n"
"    border-width: 2px;\n"
"    border-radius: 16px;\n"
"}")
        self.mainLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mainLabel.setObjectName("mainLabel")
        self.verticalLayout.addWidget(self.mainLabel)
        self.label = QtWidgets.QLabel(parent=self.textFrame)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {color: white}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.textFrame)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calcBtn.setText(_translate("MainWindow", "Калькулятор"))
        self.graphBtn.setText(_translate("MainWindow", "Графики"))
        self.eqBtn.setText(_translate("MainWindow", "Уравнения"))
        self.forLibBtn.setText(_translate("MainWindow", "Библиотека формул"))
        self.bookLibButton.setText(_translate("MainWindow", "Библиотека учебников"))
        self.mainLabel.setText(_translate("MainWindow", "Универсальный помощник в учёбе"))
        self.label.setText(_translate("MainWindow", "Выберите вкладку слева"))
